server:
  port: 8080

eureka:
  client:
    enabled: false

spring:
  cloud:
    gateway:
      routes:
        - id: shop-admin-app
          uri: http://localhost:8082/admin
          predicates:
            - Path=/admin/**
          filters:
            - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,
        - id: shop-picture-service
          uri: http://localhost:8083/api/v1/picture
          predicates:
            - Path=/api/v1/picture/**
        - id: shop-backend-api
          uri: http://localhost:8081/api/v1
          predicates:
            - Path=/api/v1/**
        - id: shop-backend-api-ws
          uri: ws://localhost:8081/api/v1/socket-channel
          predicates:
            - Path=/api/v1/socket-channel/**